String generatedModuleTemplate(Set<String> dependencies, Set<String> modules) {
  return '''
// generated by otter_json_generator
// don't make change on this manually
  
import 'package:otter_json/otter_json.dart';
${dependencies.join('\n')}

class OtterGeneratedJsonModule implements GeneratedJsonModule {
  @override
  Map<String, JsonSerializer> serializers() {
    return {
${modules.join('\n')}
    };
  }
}

''';
}

String jsonSerializerTemplate(String name, String encode, String decode) {
  return '''

class ${name}JsonSerializer implements JsonSerializer<$name, Map<String, dynamic>> {
  @override
  ${name} decode(Map<String, dynamic> output) {
    $decode
  }

  @override
  Map<String, dynamic> encode(${name} input) {
    $encode
  }
}

''';
}
