name: otter_json_generator
description: JSON serialization with code generation. Separate generated code from source and keep everything clean.
version: 2.0.0
homepage: https://github.com/hokamc/otter_json

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  otter_json:
    path: ../otter_json
  glob:
  analyzer: ^2.0.0
  build: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
