name: otter_json_generator
description: JSON serialization with code generation. Separate generated code from source and keep everything clean.
version: 1.0.1
homepage: https://github.com/hokamc/otter_json

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  otter_json: ^1.0.1

  build: ^1.5.1
  build_runner: ^1.10.6
  analyzer: ^0.40.6
  source_gen: ^0.9.8
  glob: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
