name: otter_json_generator
description: JSON serialization with code generation. Separate generated code from source and keep everything clean.
version: 1.0.3
homepage: https://github.com/hokamc/otter_json

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  otter_json: ^1.0.3
  glob: ^1.2.0
  analyzer: ^0.40.6
  build: ^1.5.1
  source_gen: ^0.9.8

dev_dependencies:
  build_runner: ^1.10.6
