name: otter_json
description: JSON serialization with code generation. Separate generated code from source and keep everything clean.
version: 2.0.0
homepage: https://github.com/hokamc/otter_json

environment:
  sdk: ">=2.14.0 <3.0.0"

