name: otter_json
description: JSON serialization with code generation. Separate generated code from source and keep everything clean.
version: 1.0.2
homepage: https://github.com/hokamc/otter_json

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
